import { describe, it, expect, vi } from 'vitest';
import fc from 'fast-check';
import jwt from 'jsonwebtoken';

// Mock the env module before importing auth functions
vi.mock('../../config/env.js', () => ({
  env: {
    JWT_SECRET: 'test-secret-key-for-property-testing',
    JWT_EXPIRES_IN: '7d',
  },
}));

import { generateToken, verifyToken } from '../auth.js';

describe('Feature: m1-project-setup-core-architecture, Property 3: Valid Login Returns JWT with Role', () => {
  /**
   * **Validates: Requirements 2.1, 2.6**
   *
   * For any userId (UUID-like string) and role ('admin'|'learner'),
   * generateToken({userId, role}) produces a token that when decoded
   * contains the same userId and role.
   */
  it('generateToken produces a token containing the same userId and role', () => {
    fc.assert(
      fc.property(
        fc.uuid(),
        fc.constantFrom('admin', 'learner'),
        (userId, role) => {
          const token = generateToken({ userId, role });

          // Token should be a non-empty string
          expect(typeof token).toBe('string');
          expect(token.length).toBeGreaterThan(0);

          // Decode and verify the token contains the correct payload
          const decoded = jwt.verify(token, 'test-secret-key-for-property-testing') as {
            userId: string;
            role: string;
          };

          expect(decoded.userId).toBe(userId);
          expect(decoded.role).toBe(role);
        }
      ),
      { numRuns: 100 }
    );
  });
});

describe('Feature: m1-project-setup-core-architecture, Property 4: Invalid JWT is Rejected', () => {
  /**
   * **Validates: Requirements 2.7, 2.8**
   *
   * For any random string that is NOT a valid JWT, verifyToken(randomString)
   * returns null. For any valid token generated by generateToken, verifyToken
   * returns the correct payload.
   */
  it('verifyToken returns null for any random non-JWT string', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1, maxLength: 200 }).filter((s) => {
          // Filter out strings that happen to be valid JWTs (extremely unlikely but safe)
          const parts = s.split('.');
          return parts.length !== 3;
        }),
        (randomString) => {
          const result = verifyToken(randomString);
          expect(result).toBeNull();
        }
      ),
      { numRuns: 100 }
    );
  });

  it('verifyToken returns correct payload for any valid token from generateToken', () => {
    fc.assert(
      fc.property(
        fc.uuid(),
        fc.constantFrom('admin', 'learner'),
        (userId, role) => {
          const token = generateToken({ userId, role });
          const result = verifyToken(token);

          expect(result).not.toBeNull();
          expect(result!.userId).toBe(userId);
          expect(result!.role).toBe(role);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('verifyToken returns null for tokens signed with a different secret', () => {
    fc.assert(
      fc.property(
        fc.uuid(),
        fc.constantFrom('admin', 'learner'),
        fc.string({ minLength: 10, maxLength: 50 }).filter(
          (s) => s !== 'test-secret-key-for-property-testing'
        ),
        (userId, role, wrongSecret) => {
          const token = jwt.sign({ userId, role }, wrongSecret);
          const result = verifyToken(token);
          expect(result).toBeNull();
        }
      ),
      { numRuns: 100 }
    );
  });
});
